In [1]:
# Print Hello world
print("Hello world")

Hello world


In [3]:
# Import NumPy
import numpy as np

In [5]:
# Create a sequence of even numbers
n = np.arange(0, 30, 2)
print(n)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [6]:
# Reshape the sequence to a 3x5 array
n = n.reshape(3, 5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [7]:
# Generate 9 evenly spaced values from 0 to 10
lspace = np.linspace(0, 10, 9)
lspace

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [8]:
# Generate 15 evenly spaced values from 1 to 4
lspace = np.linspace(1, 4, 15)
lspace

array([1.        , 1.21428571, 1.42857143, 1.64285714, 1.85714286,
       2.07142857, 2.28571429, 2.5       , 2.71428571, 2.92857143,
       3.14285714, 3.35714286, 3.57142857, 3.78571429, 4.        ])

In [10]:
# Reshape the linearly spaced array to 3x5
lspace = lspace.reshape(3, 5)

In [11]:
# Display the reshaped array
lspace

array([[1.        , 1.21428571, 1.42857143, 1.64285714, 1.85714286],
       [2.07142857, 2.28571429, 2.5       , 2.71428571, 2.92857143],
       [3.14285714, 3.35714286, 3.57142857, 3.78571429, 4.        ]])

In [14]:
# Create an array of ones with shape (2, 8)
np.ones((2, 8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
# Create a matrix of zeros with shape (7, 3)
np.zeros((7, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# Create a custom 3x3 matrix
num = np.matrix([[1, 6, 7],
                 [3, 1, 99],
                 [87, 33, 21]])

In [21]:
# Display the matrix
num

matrix([[ 1,  6,  7],
        [ 3,  1, 99],
        [87, 33, 21]])

In [22]:
# Check the array type
type(num)

numpy.matrix

In [23]:
# Print the main diagonal
print("Main diagonal elements", np.diag(num))

Main diagonal elements [ 1  1 21]


In [24]:
# Print the diagonal above the main diagonal
print("Diagnoal elements above main diagonal", np.diag(num, 1))

Diagnoal elements above main diagonal [ 6 99]


In [25]:
# Print the diagonal below the main diagonal
print("Diagnoal elements below main diagnoal", np.diag(num, -2))

Diagnoal elements below main diagnoal [87]


In [27]:
# Repeat row values three times
np.array([1, 2, 3, 4]*3)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [28]:
# Repeat a 2D array three times
np.array([[1, 2, 3, 4],
          [5, 6, 7, 8]]*3)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
# Repeat values with np.repeat
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [30]:
# Stack two matrices vertically
np.vstack([num, 3*num])

matrix([[  1,   6,   7],
        [  3,   1,  99],
        [ 87,  33,  21],
        [  3,  18,  21],
        [  9,   3, 297],
        [261,  99,  63]])

In [31]:
# Stack two matrices horizontally
np.hstack([num, 3*num])

matrix([[  1,   6,   7,   3,  18,  21],
        [  3,   1,  99,   9,   3, 297],
        [ 87,  33,  21, 261,  99,  63]])

In [33]:
# Initialize a ones matrix of shape (3, 4)
p = np.ones((3,4))
p

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
# Horizontally stack several matrices
np.hstack([num, 3*num, 2*p])

matrix([[  1.,   6.,   7.,   3.,  18.,  21.,   2.,   2.,   2.,   2.],
        [  3.,   1.,  99.,   9.,   3., 297.,   2.,   2.,   2.,   2.],
        [ 87.,  33.,  21., 261.,  99.,  63.,   2.,   2.,   2.,   2.]])

In [35]:
# Create a zeros array of shape (2, 3)
x = np.zeros((2, 3))

In [36]:
# Display the zeros array
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
# Create a ones array of shape (2, 3)
y = np.ones((2, 3))
y

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
# Display the ones array
print(x*y)

[[0. 0. 0.]
 [0. 0. 0.]]


In [42]:
# Multiply arrays element-wise
print(x+y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [43]:
# Add arrays element-wise
print(y-x)

[[1. 1. 1.]
 [1. 1. 1.]]


In [44]:
# Subtract arrays element-wise
print(x/y)

[[0. 0. 0.]
 [0. 0. 0.]]


In [45]:
# Divide arrays element-wise
print(y/x)

[[inf inf inf]
 [inf inf inf]]


/tmp/ipykernel_11744/295437148.py:1: RuntimeWarning: divide by zero encountered in divide
  print(y/x)


In [ ]:
# Divide by zero in the array
z = np.ones((2,3))
z

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
# Create a ones array for matrix operations
y

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
# Display matrix y
y.dot(z)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [56]:
# Compute matrix multiplication with dot
a = np.ones((3, 2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [57]:
# Create a 3x2 array of ones
print(a@z)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [58]:
# Multiply matrix a by z
a.dot(y)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [59]:
# Compute dot product of a and y
z = np.array([y, y**2])

In [60]:
# Create a stacked array of y and y squared
z

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [61]:
# Display z
print(len(z))

2


In [62]:
# Get the length of z
z.shape

(2, 2, 3)

In [63]:
# Show the shape of z
z.T

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [64]:
# Transpose z
z.T.shape

(3, 2, 2)

In [65]:
# Check the transposed shape
z.dtype

dtype('float64')

In [66]:
# Inspect the dtype of z
z = z.astype('i')
z.dtype

dtype('int32')

In [67]:
# Cast z to integer type
a = np.array([-4, -2, 1, 3, 5])
a.sum()

np.int64(3)

In [68]:
# Create a numeric array and compute sum
a.max()

np.int64(5)

In [69]:
# Find the maximum value
a.min()

np.int64(-4)

In [70]:
# Find the minimum value
a.mean()

np.float64(0.6)

In [71]:
# Compute the mean
a.medidan()

AttributeError: 'numpy.ndarray' object has no attribute 'medidan'

In [72]:
# Attempt to compute median
a.std()

np.float64(3.2619012860600183)

In [73]:
# Compute standard deviation
a.argmin()

np.int64(0)

In [74]:
# Find argmin index
a.argmax()

np.int64(4)

In [75]:
# Find argmax index
x = [7, 3, -2, 0, 100, 25]

In [76]:
# Create a list x
x = np.array(x)

In [77]:
# Convert x to a NumPy array
x.argmax()

np.int64(4)

In [78]:
# Find the argmax in x
x.argmin()

np.int64(2)

In [79]:
# Find the argmin in x
y = [7, 3, -2, 0, 100, 25]

In [81]:
# Create list y
y.max

AttributeError: 'list' object has no attribute 'max'

In [82]:
# Access y.max
s = np.arange(100)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [83]:
# Create a range of 100 integers
s = np.arange(6)**3
s

array([  0,   1,   8,  27,  64, 125])

In [84]:
# Create cubes from 0 to 5
s[1:5]

array([ 1,  8, 27, 64])

In [85]:
# Slice s from index 1 to 4
s[::-1]

array([125,  64,  27,   8,   1,   0])

In [86]:
# Reverse the array
s[:2:]

array([0, 1])

In [87]:
# Slice with step
s[:3:-1]

array([125,  64])

In [88]:
# Slice with reverse from index 3
s[:2:-1]

array([125,  64,  27])

In [89]:
# Slice with reverse starting from the end
s

array([  0,   1,   8,  27,  64, 125])

In [90]:
# Display the array
s[]

SyntaxError: invalid syntax (1085298815.py, line 1)

In [91]:
# Access an empty slice
s[0:]

array([  0,   1,   8,  27,  64, 125])

In [92]:
# Access from start to end
s[1:].mean()

np.float64(45.0)

In [ ]:
# Compute mean of s[1:]
s[1:].mean()

np.float64(45.0)

In [93]:
# Compute mean of s[1:] again
s

array([  0,   1,   8,  27,  64, 125])

In [94]:
# Display the array
s.argmax()

np.int64(5)

In [95]:
# Find the index of the maximum value
s[:3:-1].argmin()

np.int64(1)

In [96]:
# Find the minimum index in a reversed slice
s[1:].argmin()

np.int64(0)

In [97]:
# Find argmin on s[1:]
s

array([  0,   1,   8,  27,  64, 125])

In [98]:
# Display the original array
s = np.arange(55)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54])

In [99]:
# Create range 0..54
s.reshape(11, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54]])

In [102]:
# Reshape the range to 11x5
s[3]

np.int64(3)

In [105]:
# Access the 4th row
s.shape

(55,)

In [106]:
# Check the array shape
s.resize(11, 5)

In [107]:
# Resize the array to 11x5
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54]])

In [108]:
# Display the resized array
s[3, 4]

np.int64(19)

In [109]:
# Access element (3, 4)
s[3][4]

np.int64(19)

In [110]:
# Access the same element via row slicing
s[3, 3:5]

array([18, 19])

In [111]:
# Slice row 3 from columns 3:5
s[3, 1:5]

array([16, 17, 18, 19])

In [113]:
# Slice row 3 from columns 1:5
s[:3, :-1]

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])