In [1]:
#assignment 1

In [2]:
import numpy as np

In [3]:
arr1 = np.full((2, 2), 7)

In [4]:
arr1

array([[7, 7],
       [7, 7]])

In [5]:
random_matrix = np.random.rand(2, 2)

In [6]:
random_matrix

array([[0.69374167, 0.8137646 ],
       [0.46399151, 0.38976697]])

In [7]:
#3
arr2 = np.arange(10, 51)

print(arr2)

print(len(arr2))

print(arr2.shape)

print(arr2.dtype)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
41
(41,)
int64


In [12]:
#4

ar3 = np.zeros(10)
print(ar3)

ar4 = np.ones((3, 3))
print(ar4)

ar5 = np.ones((4, 4))
print(ar5)

ar6 = np.arange(5, 51, 5)
print(ar6)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[ 5 10 15 20 25 30 35 40 45 50]


In [18]:
#5

ar7 = np.arange(1, 25)
print(ar7)

ar7 = ar7.reshape(4, 6)
print(ar7)
print(np.ndim(ar7))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
2


In [20]:
ar8 = ar7.reshape(6, 4)
print(ar8)
print(np.ndim(ar8))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
2


In [22]:
ar9 = ar8.reshape(2, 3, 4)
print(ar9)
print(np.ndim(ar9))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
3


In [29]:
#6
marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])

In [25]:
marks[:1]

array([78])

In [28]:
marks[-1]

np.int64(81)

In [30]:
marks[2]

np.int64(92)

In [33]:
marks[:4]

array([78, 85, 92, 67])

In [38]:
marks[-3:]

array([73, 95, 81])

In [39]:
#7

a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

In [40]:
print(
a + b, 
a - b, 
a * b, 
a / b)

[15 30 45 60 75] [ 5 10 15 20 25] [  50  200  450  800 1250] [2. 2. 2. 2. 2.]


In [41]:
print(a**2, b**2)

[ 100  400  900 1600 2500] [ 25 100 225 400 625]


In [42]:
#8

salary = np.array([25000, 32000, 28000, 45000,
                   50000, 38000, 42000, 30000])

In [43]:
print("Total salary:", salary.sum())

Total salary: 290000


In [44]:
print("Average salary:", salary.mean())

Average salary: 36250.0


In [45]:
print("Highest and lowest salary:", salary.max(), salary.min())

Highest and lowest salary: 50000 25000


In [46]:
print("Media and std dev of salary:", np.median(salary), np.std(salary))

Media and std dev of salary: 35000.0 8317.902379807063


In [47]:
#9

marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])